openapi: "3.0.2"
info:
  title: SIO06 Prometheus Metrics API
  version: "0.0.1"
  description: |-
    This is the API documentation to get prometheus metrics from SIO06 devices using HTTP.

    The API is available at http://my-io4edge-device:9100/metrics.

servers:
  - url: http://my-io4edge-device:9100/metrics
    description: Example SIO06

paths:
  /metrics:
    get:
      summary: Get prometheus metrics
      description: |-
        Get prometheus metrics from the device.

        The metrics are served in the prometheus text format.

        List of metrics is shown in the example response (Firmware sio06_01_default version 1.1.1)
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |-
                  # HELP reset_count Number of resets occurred
                  # TYPE reset_count counter
                  reset_count{reason="unknown"} 0
                  reset_count{reason="poweron"} 5
                  reset_count{reason="external"} 0
                  reset_count{reason="software"} 3
                  reset_count{reason="panic"} 0
                  reset_count{reason="interruptwd"} 0
                  reset_count{reason="taskwd"} 0
                  reset_count{reason="wd"} 0
                  reset_count{reason="deepsleep"} 0
                  reset_count{reason="brownout"} 0
                  reset_count{reason="sdio"} 0
                  reset_count{reason="usb"} 119
                  reset_count{reason="jtag"} 0
                  reset_count{reason="efuse"} 0
                  reset_count{reason="powerglitch"} 0
                  reset_count{reason="cpulockup"} 0
                  # HELP free_heap_bytes Free heap (bytes)
                  # TYPE free_heap_bytes gauge
                  free_heap_bytes{} 246368
                  # HELP up_seconds uptime (seconds)
                  # TYPE up_seconds counter
                  up_seconds{} 432.457876
                  # HELP number_packets_received Number of trdp packets received at the sink
                  # TYPE number_packets_received counter
                  number_packets_received{type="good"} 141
                  number_packets_received{type="lost"} 23
                  number_packets_received{type="seq_resync"} 4
                  number_packets_received{type="bad_crc"} 0
                  number_packets_received{type="bad_comid"} 0
                  number_packets_received{type="bad_version"} 0
                  number_packets_received{type="bad_type"} 0
                  number_packets_received{type="short"} 0
                  number_packets_received{type="bad_len"} 0
                  number_packets_received{type="seq_old"} 0
                  # HELP number_packets_published Number of published trdp packets from the source
                  # TYPE number_packets_published counter
                  number_packets_published{type="good"} 2137
                  number_packets_published{type="failed"} 11
                  # HELP ana Analog input values(-1 to 1)
                  # TYPE ana gauge
                  ana{channel="ch1"} -0.004237
                  ana{channel="ch2"} -0.004250
                  # HELP bin Digital input values (Bitmask)
                  # TYPE bin gauge
                  bin{} 0
                  # HELP relay Desired relay states (Bitmask)
                  # TYPE relay gauge
                  relay{} 0
                  # HELP adc_errors ADC errors
                  # TYPE adc_errors counter
                  adc_errors{type="spi"} 0
                  adc_errors{type="tout"} 0
        "500":
          description: Internal Server Error

