openapi: "3.0.2"
info:
  title: SIO04 Prometheus Metrics API
  version: "1.0"
  description: |-
    This is the API documentation to get prometheus metrics from SIO04 devices using HTTP.

    The API is available at http://my-io4edge-device:9100/metrics.

servers:
  - url: http://my-io4edge-device:9100/metrics
    description: Example SIO04

paths:
  /metrics:
    get:
      summary: Get prometheus metrics
      description: |-
        Get prometheus metrics from the device.

        The metrics are served in the prometheus text format.

        Detailed list of metrics is TBD
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |-
                  # HELP gnss_fix_type_enum GNSS fix type (0-7)
                  # TYPE gnss_fix_type_enum gauge
                  gnss_fix_type_enum{} 1
                  # HELP gnss_eph_meters GNSS estimated horizontal position error (m)
                  # TYPE gnss_eph_meters gauge
                  gnss_eph_meters{} 3.800000
                  # HELP gnss_lat_degrees GNSS latidude (deg)
                  # TYPE gnss_lat_degrees gauge
                  gnss_lat_degrees{} 49.430775
                  # HELP gnss_lon_degrees GNSS longitude (deg)
                  # TYPE gnss_lon_degrees gauge
                  gnss_lon_degrees{} 11.071074
        "500":
          description: Internal Server Error

