openapi: "3.0.2"
info:
  title: SIO04 Management API
  version: "0.0.1"
  description: |-
    This is the API documentation to manage SIO04 devices via HTTPS.
    This API does not serve metrics. For performance reasons, metrics are served at http://my-io4edge-device:9100/metrics.

    The API is secured with basic auth with a single user name and password.
    - user: "io4edge", default password: "core"

    The password can be changed with the PATCH /users/io4edge/basic_auth endpoint.

    The API is available at https://my-io4edge-device/api/v1

    Performance note: Due to hardware limitations, the initial TLS handshake can take up to 2 seconds.
    Clients should reuse the TLS session where possible to avoid this delay.

servers:
  - url: https://my-io4edge-device/api/v1
    description: Example SIO04
tags:
  - name: core
    description: Common io4edge API
  - name: app
    description: Application specific API

paths:
  /users/{user}/basic_auth:
    $ref: "./core/paths/auth_basic.yml"
  /certificate:
    $ref: "./core/paths/certificate.yml"
  /key:
    $ref: "./core/paths/key.yml"
  /firmware:
    $ref: "./core/paths/firmware.yml"
  /hardware:
    $ref: "./time_positioning_device/paths/hardware.yml"
  /command/restart:
    $ref: "./core/paths/command_restart.yml"
  /command/repl:
    $ref: "./time_positioning_device/paths/command_repl.yml"
  /parameter/{parameter}:
    $ref: "./time_positioning_device/paths/parameter.yml"
  /tps/configuration:
    $ref: "./time_positioning_device/paths/configuration.yml"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
