openapi: "3.0.2"
info:
  title: SIO06 Prometheus Metrics API
  version: "0.0.1"
  description: |-
    This is the API documentation to get prometheus metrics from SIO06 devices using HTTP.

    The API is available at http://my-io4edge-device:9100/metrics.

servers:
  - url: http://my-io4edge-device:9100/metrics
    description: Example SIO06

paths:
  /metrics:
    get:
      summary: Get prometheus metrics
      description: |-
        Get prometheus metrics from the device.

        The metrics are served in the prometheus text format.

        List of metrics is shown in the example response.
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |-
                  # HELP free_heap_bytes Free heap (bytes)
                  # TYPE free_heap_bytes gauge
                  free_heap_bytes{} 262368
                  # HELP number_pakcets_received Number of the relay control messages received at the trdp sink
                  # TYPE number_pakcets_received counter
                  number_pakcets_received{} 0
                  # HELP number_packets_published Number of successful published trdp packets from the source
                  # TYPE number_packets_published counter
                  number_packets_published{} 17
                  # HELP ana Analog input values(-1 to 1)
                  # TYPE ana gauge
                  ana{channel="ch1"} -0.004149
                  ana{channel="ch2"} -0.004166
                  # HELP bin Digital input values (Bitmask)
                  # TYPE bin gauge
                  bin{} 0
                  # HELP relay Desired relay states (Bitmask)
                  # TYPE relay gauge
                  relay{} 0
        "500":
          description: Internal Server Error

