openapi: "3.0.2"
info:
  title: SIO06 Prometheus Metrics API
  version: "0.0.1"
  description: |-
    This is the API documentation to get prometheus metrics from SIO06 devices using HTTP.

    The API is available at http://my-io4edge-device:9100/metrics.

servers:
  - url: http://my-io4edge-device:9100/metrics
    description: Example SIO06

paths:
  /metrics:
    get:
      summary: Get prometheus metrics
      description: |-
        Get prometheus metrics from the device.

        The metrics are served in the prometheus text format.

        List of metrics is shown in the example response (Firmware sio06_01_default version 1.0.0)
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: |-
                  # HELP free_heap_bytes Free heap (bytes)
                  # TYPE free_heap_bytes gauge
                  free_heap_bytes{} 251568
                  # HELP up_seconds uptime (seconds)
                  # TYPE up_seconds counter
                  up_seconds{} 307.812578
                  # HELP number_packets_received Number of trdp packets received at the sink
                  # TYPE number_packets_received counter
                  number_packets_received{type="good"} 170
                  number_packets_received{type="bad_crc"} 36
                  number_packets_received{type="bad_comid"} 0
                  number_packets_received{type="bad_version"} 0
                  number_packets_received{type="bad_type"} 42
                  number_packets_received{type="short"} 0
                  number_packets_received{type="bad_len"} 0
                  # HELP number_packets_published Number of published trdp packets from the source
                  # TYPE number_packets_published counter
                  number_packets_published{type="good"} 1512
                  number_packets_published{type="failed"} 18
                  # HELP ana Analog input values(-1 to 1)
                  # TYPE ana gauge
                  ana{channel="ch1"} -0.004278
                  ana{channel="ch2"} 1.248239
                  # HELP bin Digital input values (Bitmask)
                  # TYPE bin gauge
                  bin{} 0
                  # HELP relay Desired relay states (Bitmask)
                  # TYPE relay gauge
                  relay{} 0
                  # HELP adc_errors ADC errors
                  # TYPE adc_errors counter
                  adc_errors{type="spi"} 0
                  adc_errors{type="tout"} 0
        "500":
          description: Internal Server Error

