get:
  tags:
    - vwu
  summary: Get configuration of vehicle wakeup unit
  description: |-
    Get configuration version and parameters of the device and list the parameters that are not supported 
    by the firmware or missing in configuration.

    Parameters not set by the user will have the default value and will appear in the missing_parameters list.

    Parameters set with invalid values will retain their default value and will appear in the invalid_parameters list.

    Parameters not supported by the firmware will be ignored and will appear in the unsupported_parameters list.

    Available parameters, with their default values in brackets, are:
    - rel-hold [2.0] - (e.g. "1.0") time in seconds until relay is deactivated
    - rel-comid [TBD] - (e.g. "A2F66F23") ComID of TRDP relay sink, in hex notation
    - input-comid [TBD]- (e.g. "A2F66F24") ComID of TRDP "inputs" source, in hex notation
    - input-pubper [1.0] - (e.g. "3.2") publishing period of TRDP "inputs" in Hz

  security:
    - basicAuth: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../core/components.yml#/components/schemas/ConfigurationGet"

    "401":
      $ref: "../../core/responses/unauthorized.yml"
    "500":
      $ref: "../../core/responses/internal_server_error.yml"
put:
  tags:
    - vwu
  summary: Load configuration of vehicle wakeup unit
  description: |-
    Upload configuration to device.
    Client should call configuration GET endpoint to check if the configuration was applied successfully.
    See GET /configuration for available parameters and the behaviour for missing, unsupported and invalid parameters.

    The new parameters can be read back immediately after the PUT request, but they will not be applied until the device is restarted.

  security:
    - basicAuth: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../components.yml#/components/schemas/ConfigurationPut"
  responses:
    "200":
      description: OK
    "400":
      description: Invalid configuration
      content:
        application/json:
          schema:
            $ref: "../components.yml#/components/schemas/ErrorInfo"
    "401":
      $ref: "../../core/responses/unauthorized.yml"
    "500":
      $ref: "../../core/responses/internal_server_error.yml"
