get:
  tags:
    - vwu
  summary: Get configuration of vehicle wakeup unit
  description: |-
    Get configuration version and parameters of the device and list the parameters that are not supported 
    by the firmware or missing in configuration.

    Available parameters:
    - rel-hold - (e.g. "1.0") time in seconds until relay is deactivated
    - rel-comid - (e.g. "A2F66F23") ComID of TRDP relay sink, in hex notation
    - input-comid - (e.g. "A2F66F24") ComID of TRDP "inputs" source, in hex notation
    - input-pubper - (e.g. "3.2") publishing period of TRDP "inputs" in Hz
   
  security:
    - basicAuth: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../../core/schemas/configuration.yml"
              - type: object
                properties:
                  unsupported_parameters:
                    description: |-
                      List of parameters in configuration that are not supported by the firmware, (e.g.
                      because the firmware is too old).
                    type: array
                    items:
                      type: string
                    example: ["parameter3", "parameter4"]
                  missing_parameters:
                    description: List of parameters that are expected by firmware but missing in configuration.
                    type: array
                    items:
                      type: string
                    example: ["parameter5"]
    "401":
      $ref: "../../core/responses/unauthorized.yml"
    "500":
      $ref: "../../core/responses/internal_server_error.yml"
put:
  tags:
    - vwu
  summary: Load configuration of vehicle wakeup unit
  description: |-
    Upload configuration to device.
    Client should call configuration GET endpoint to check if the configuration was applied successfully.
    See GET /configuration for available parameters.

    If a parameter is not set in the configuration, the default value will be used.

    If a parameter contains an invalid value, the configuration will not be applied and the device will return an error.

    If a parameter is not supported by the firmware, the configuration will be appplied, but the parameter will be ignored.

    The device should be restarted after configuration is applied.

  security:
    - basicAuth: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../schemas/configuration.yml"
  responses:
    "200":
      description: OK
    "400":
      description: Invalid configuration
      content:
        application/json:
          schema:
            $ref: "../../core/schemas/error_info.yml"
    "401":
      $ref: "../../core/responses/unauthorized.yml"
    "500":
      $ref: "../../core/responses/internal_server_error.yml"
